name: SkinsRestorer
main: skinsrestorer.bukkit.SkinsRestorer
version: 10.3
author: _Shevchik_
softdepend: [ProtocolSupport, ProtocolLib]
load: startup
commands:
  skinsrestorer:
    aliases: [sr]
  skin: